FROST_APP_GROUP=com.footprintcat.frostiot
FROST_APP_VERSION=0.0.1-SNAPSHOT
# Why add `-SNAPSHOT` suffix?
# see: https://central.sonatype.org/publish/publish-portal-snapshots/

# 打包时通过命令行参数传入
# refer: https://github.com/vanniktech/gradle-maven-publish-plugin/issues/800#issuecomment-2394004304
# signing.keyId=
# signing.password=
# signing.secretKeyRingFile=/Users/mac/.gnupg/secring.gpg

#
# 增加以下配置以加快编译速度
# docs: https://docs.gradle.org.cn/current/userguide/performance.html
#

# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
# Default value: -Xmx512m -XX:MaxMetaspaceSize=256m
# docs:
# - https://docs.gradle.org.cn/current/userguide/performance.html#increase_heap_size
# - https://docs.gradle.org.cn/current/userguide/config_gradle.html#sec:configuring_jvm_memory
org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8

# 配置守护进程
# 效果：Gradle守护进程会在后台运行，避免每次构建时都重新启动JVM，从而加快构建速度。
# 副作用：一般没有明显的副作用，但在CI环境中建议禁用，因为守护进程可能会导致构建结果不一致。
# docs: https://docs.gradle.org.cn/current/userguide/performance.html#enable_daemon
org.gradle.daemon=false

# 启用并行构建
# 效果：允许Gradle在多线程环境下并行执行任务，显著减少构建时间。
# 副作用：并行构建要求项目之间没有依赖关系，否则可能会导致构建失败或不稳定。
# docs: https://docs.gradle.org.cn/current/userguide/performance.html#sec:enable_parallel_execution
org.gradle.parallel=true

# 按需配置
# 效果：Gradle只会配置当前构建所需的项目，减少大型多项目构建的配置时间。
# 副作用：如果项目之间有复杂的依赖关系，可能会导致一些任务无法正确执行。
org.gradle.configureondemand=true

# 使用新的配置缓存
# 效果：Gradle会缓存任务的输出结果，避免重复执行相同的任务，从而加快构建速度。
# 副作用：缓存可能会导致一些任务在代码或配置发生变化后没有被重新执行，建议在开发过程中定期清理缓存。
# docs: https://docs.gradle.org.cn/current/userguide/performance.html#enable_build_cache
org.gradle.caching=true
