FROST_APP_GROUP=com.footprintcat.frostiot
FROST_APP_VERSION=0.0.1-SNAPSHOT
# Why add `-SNAPSHOT` suffix?
# see: https://central.sonatype.org/publish/publish-portal-snapshots/

# 打包时通过命令行参数传入
# refer: https://github.com/vanniktech/gradle-maven-publish-plugin/issues/800#issuecomment-2394004304
# signing.keyId=
# signing.password=
# signing.secretKeyRingFile=/Users/mac/.gnupg/secring.gpg
