rootProject.name = 'frost-iot'

dependencyResolutionManagement {
    repositories {
        mavenLocal()
        maven { url = "https://maven.aliyun.com/repository/public" }
        maven { url = "https://maven.aliyun.com/repository/gradle-plugin" }
        maven { url = "https://plugins.gradle.org/m2/" }
        mavenCentral()
    }
}

buildscript {
    repositories {
        mavenLocal()
        maven { url = "https://maven.aliyun.com/repository/public" }
        maven { url = "https://maven.aliyun.com/repository/gradle-plugin" }
        maven { url = "https://plugins.gradle.org/m2/" }
        mavenCentral()
    }

    dependencies {
        classpath "tech.yanand.maven-central-publish:tech.yanand.maven-central-publish.gradle.plugin:1.3.0"
    }
}

// Common 工具类
include 'common'
// adapter SPI 接口
include 'frost-iot-adapter-sdk' // 发布组件

// Frost IoT 核心
include 'frost-iot-core' // 发布组件
// Frost IoT 适配器
// include 'frost-iot-adapter'
// include 'frost-iot-adapter:frost-iot-adapter-mqtt' // 发布组件

// Frost BOM 依赖版本定义
include 'frost-iot-dependencies'
