plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.4'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = "${FROST_APP_GROUP}.manager"
version = FROST_APP_VERSION

repositories {
    mavenCentral()
}

dependencies {
    // implementation platform(...) 仅传递版本约束，不传递实际依赖。例如: 统一版本管理（BOM）
    // implementation project(...)  传递所有依赖（代码 + 依赖项）

    // 必需依赖
    // implementation platform(project(":frost-iot-dependencies"))
    implementation project(":frost-iot-dependencies")
    implementation project(":common")

    // Spring Boot 相关依赖
    implementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // 其他业务依赖
    // ...
}

tasks.named('test') {
    useJUnitPlatform()
}
