# docs: https://docs.micronaut.io/4.8.2/guide/configurationreference.html
micronaut:
  application:
    name: frost-iot-core
    default-charset: UTF-8
  server:
    port: 8666

  # Open API 配置
  # docs: https://micronaut-projects.github.io/micronaut-openapi/latest/guide/
  openapi:
    views:
      spec: >
        swagger-ui.enabled=true,
        redoc.enabled=true,
        redoc.js.url=/redoc/res/,
        openapi-explorer.enabled=true,
        openapi-explorer.js.url=/openapi-explorer/res/,
        scalar.enabled=true,
        scalar.js.url=/scalar/res/,
        rapidoc.enabled=true,
        rapidoc.js.url=/rapidoc/res/,
        rapidoc.bg-color=#14191f,
        rapidoc.text-color=#aec2e0,
        rapidoc.sort-endpoints-by=method
  router:
    # API 版本化
    # docs: https://micronaut.bookhub.tech/core/httpserver/apiVersioning
    versioning:
      enabled: true
      default-version: 1
      # parameter:
      #   enabled: false
      #   names: 'v,api-version'
      header:
        enabled: true
        names:
          - 'X-API-VERSION'
          # - 'Accept-Version'
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      # swagger-ui
      # http://localhost:8666/swagger-ui/index.html
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
      # redoc
      # http://localhost:8666/redoc
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      # openapi-explorer
      # http://localhost:8666/openapi-explorer
      openapi-explorer:
        paths: classpath:META-INF/swagger/views/openapi-explorer
        mapping: /openapi-explorer/**
      # scalar
      # http://localhost:8666/scalar
      scalar:
        paths: classpath:META-INF/swagger/views/scalar
        mapping: /scalar/**
      # RapiDoc
      # http://localhost:8666/rapidoc
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**

datasources:
  default:
    url: jdbc:postgresql://127.0.0.1:5432/frostiot_dev
    driverClassName: org.postgresql.Driver
    username: frostiot
    password: frostiot

frost-iot:
  # Frost IoT 版本号
  version: 1.0.0
  profile-name: "默认配置文件（application.yml）"
  api:
    # Api 文档版本号
    version: 1.0.0
