micronaut.application.name=frost-iot-core
micronaut.server.port=8666
micronaut.application.default-charset=UTF-8
#
# Open API 配置
micronaut.openapi.views.spec=\
  swagger-ui.enabled=true, \
  redoc.enabled=true, \
  openapi-explorer.enabled=true, \
  scalar.enabled=true, \
  rapidoc.enabled=true, \
  rapidoc.bg-color=#14191f, \
  rapidoc.text-color=#aec2e0, \
  rapidoc.sort-endpoints-by=method
micronaut.router.static-resources.swagger.paths=classpath:META-INF/swagger
micronaut.router.static-resources.swagger.mapping=/swagger/**
micronaut.router.static-resources.swagger.c: application/x-yaml; charset=utf-8  # 关键配置
# swagger-ui
# http://localhost:8666/swagger-ui/index.html
micronaut.router.static-resources.swagger-ui.paths=classpath:META-INF/swagger/views/swagger-ui
micronaut.router.static-resources.swagger-ui.mapping=/swagger-ui/**
# redoc
# http://localhost:8666/redoc
micronaut.router.static-resources.redoc.paths=classpath:META-INF/swagger/views/redoc
micronaut.router.static-resources.redoc.mapping=/redoc/**
# openapi-explorer
# http://localhost:8666/openapi-explorer
micronaut.router.static-resources.openapi-explorer.paths=classpath:META-INF/swagger/views/openapi-explorer
micronaut.router.static-resources.openapi-explorer.mapping=/openapi-explorer/**
# scalar
# http://localhost:8666/scalar
micronaut.router.static-resources.scalar.paths=classpath:META-INF/swagger/views/scalar
micronaut.router.static-resources.scalar.mapping=/scalar/**
# RapiDoc
# http://localhost:8666/rapidoc
micronaut.router.static-resources.rapidoc.paths=classpath:META-INF/swagger/views/rapidoc
micronaut.router.static-resources.rapidoc.mapping=/rapidoc/**
#
# Frost IoT 版本号
frost-iot.version=1.0.0
# Api 文档版本号
frost-iot.api.version=1.0.0
